<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>disable</Nullable>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Nodes\Primitive types\Logical.cs" />
      <Compile Remove="Nodes\Primitive types\Optional.cs" />
      <Compile Remove="Nodes\Primitive types\Probability.cs" />
      <Compile Remove="Nodes\Primitive types\ProbabilityOf.cs" />
      <Compile Remove="Nodes\Values\Composite\Composer.cs" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Tests" />
    </ItemGroup>

</Project>
